// <auto-generated />
using System;
using HotelBookingApp.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240928053153_reDesignBooking")]
    partial class reDesignBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagement.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvanceAmt")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HallIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainingAmt")
                        .HasColumnType("int");

                    b.Property<string>("RoomIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelManagement.Models.GorvnIdType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GorvnIdTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdType = "Pan"
                        },
                        new
                        {
                            Id = 2,
                            IdType = "Aadhar"
                        },
                        new
                        {
                            Id = 3,
                            IdType = "Voter"
                        },
                        new
                        {
                            Id = 4,
                            IdType = "Other"
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovnId")
                        .HasColumnType("int");

                    b.Property<string>("GovnIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomsRoomNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GovnId");

                    b.HasIndex("RoomsRoomNumber");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelManagement.Models.Hall", b =>
                {
                    b.Property<string>("HallNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.HasKey("HallNumber");

                    b.HasIndex("BookingId");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            HallNumber = "H1",
                            Rent = 25000
                        },
                        new
                        {
                            HallNumber = "H2",
                            Rent = 25000
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Rooms", b =>
                {
                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.HasKey("RoomNumber");

                    b.HasIndex("BookingId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomNumber = "101",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "102",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "103",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "104",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "105",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "106",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "107",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "108",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "109",
                            Rent = 1800
                        },
                        new
                        {
                            RoomNumber = "110",
                            Rent = 1800
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Guest", b =>
                {
                    b.HasOne("HotelManagement.Models.GorvnIdType", "GorvnIdType")
                        .WithMany()
                        .HasForeignKey("GovnId");

                    b.HasOne("HotelManagement.Models.Rooms", null)
                        .WithMany("Guests")
                        .HasForeignKey("RoomsRoomNumber");

                    b.Navigation("GorvnIdType");
                });

            modelBuilder.Entity("HotelManagement.Models.Hall", b =>
                {
                    b.HasOne("HotelManagement.Models.Booking", null)
                        .WithMany("Halls")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("HotelManagement.Models.Rooms", b =>
                {
                    b.HasOne("HotelManagement.Models.Booking", null)
                        .WithMany("Rooms")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("HotelManagement.Models.Booking", b =>
                {
                    b.Navigation("Halls");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagement.Models.Rooms", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
