// <auto-generated />
using System;
using HotelBookingApp.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240927094914_makesomeproperty")]
    partial class makesomeproperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagement.Models.GorvnIdType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GorvnIdTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdType = "Pan"
                        },
                        new
                        {
                            Id = 2,
                            IdType = "Aadhar"
                        },
                        new
                        {
                            Id = 3,
                            IdType = "Voter"
                        },
                        new
                        {
                            Id = 4,
                            IdType = "Other"
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovnId")
                        .HasColumnType("int");

                    b.Property<string>("GovnIdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GovnId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelManagement.Models.Hall", b =>
                {
                    b.Property<string>("HallNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HallNumber");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            HallNumber = "H1"
                        },
                        new
                        {
                            HallNumber = "H2"
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Rooms", b =>
                {
                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoomNumber");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomNumber = "101"
                        },
                        new
                        {
                            RoomNumber = "102"
                        },
                        new
                        {
                            RoomNumber = "103"
                        },
                        new
                        {
                            RoomNumber = "104"
                        },
                        new
                        {
                            RoomNumber = "105"
                        },
                        new
                        {
                            RoomNumber = "106"
                        },
                        new
                        {
                            RoomNumber = "107"
                        },
                        new
                        {
                            RoomNumber = "108"
                        },
                        new
                        {
                            RoomNumber = "109"
                        },
                        new
                        {
                            RoomNumber = "110"
                        });
                });

            modelBuilder.Entity("HotelManagement.Models.Guest", b =>
                {
                    b.HasOne("HotelManagement.Models.GorvnIdType", "GorvnIdType")
                        .WithMany()
                        .HasForeignKey("GovnId");

                    b.Navigation("GorvnIdType");
                });
#pragma warning restore 612, 618
        }
    }
}
